name: Deploy to Server

on:
  push:
    branches:
      - main
      - main-dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Setup Yarn
        run: |
          corepack enable
          corepack prepare yarn@4.6.0 --activate

      - name: Install dependencies
        run: yarn install

      - name: Build documentation site
        run: |
          echo "Debugging: listing workspace files"
          ls -la
          yarn build
        
      - name: Prepare for deployment
        run: |
          tar -czf build.tar.gz build
          
      - name: Deploy to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          source: "build.tar.gz"
          target: "/tmp"
          
      - name: Extract and deploy on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            if [ "${{ github.ref }}" = "refs/heads/main" ]; then
              DEPLOY_DIR="/var/www/prod/silvana/docs"
            elif [ "${{ github.ref }}" = "refs/heads/main-dev" ]; then
              DEPLOY_DIR="/var/www/dev/silvana/docs"
            fi
            
            mkdir -p $DEPLOY_DIR
            tar -xzf /tmp/build.tar.gz -C /tmp
            cp -r /tmp/build/* $DEPLOY_DIR/
            rm -rf /tmp/build
            rm /tmp/build.tar.gz 
